# This is a basic workflow to help you get started with Actions

name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script 
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script,${{ secrets.HOSTNAME }}
        run: |
          echo Add other actions to build,
          echo ${{ secrets.HOSTNAME }}
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.USER }} # 服务器用户名
          # pass: ${{ secrets.HOSTSECRET }} # 服务器密码
          key: ${{ secrets.KEY }}
          connect_timeout: 1000s
          source: 'aa.js' # 源路径（工作流）
          target: '/Users/shuanger/Desktop/test1111' # 目标路径（服务器）

